name: Build and Push Jetson 7.1.0 Container
permissions:
  contents: read
on:
  release:
    types: [created]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push image after build?"
        default: false
      custom_tag:
        type: string
        description: "Custom tag to use for the image (overrides VERSION)"
        default: ""

env:
  VERSION: "0.0.0" # Default version, will be overwritten
  BASE_IMAGE: "roboflow/roboflow-inference-server-jetson-7.1.0"

jobs:
  docker:
    runs-on:
      labels: depot-ubuntu-24.04-4
      group: public-depot
    timeout-minutes: 360
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v4
      - name: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python ./inference/core/version.py)" >> $GITHUB_ENV
      - name: Determine Image Tags
        id: tags
        uses: ./.github/actions/determine-tags
        with:
          custom_tag: ${{ github.event.inputs.custom_tag }}
          version: ${{ env.VERSION }}
          base_image: ${{ env.BASE_IMAGE }}
          force_push: ${{ github.event.inputs.force_push }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Build and Push
        uses: depot/build-push-action@v1
        with:
          push: ${{ github.event_name == 'release' || (github.event.inputs.force_push == 'true')}}
          project: grl7ffzxd7
          tags: ${{ steps.tags.outputs.image_tags }}
          platforms: linux/arm64
          file: ./docker/dockerfiles/Dockerfile.onnx.jetson.7.1.0
