name: Retag Jetson 6.2.0 Container
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      force_push:
        type: boolean
        description: "Do you want to push retagged image?"
        default: false

env:
  SOURCE_IMAGE: "roboflow/roboflow-inference-server-jetson:jetpack-6.2.0"
  TARGET_IMAGE: "roboflow/roboflow-inference-server-jetson-6.2.0"
  VERSION: "0.0.0" # Default version, will be overwritten

jobs:
  retag:
    runs-on:
      labels: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v4

      - name: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python ./inference/core/version.py)" >> $GITHUB_ENV

      - name: Pull source image
        run: docker pull ${{ env.SOURCE_IMAGE }}

      - name: Retag image
        run: |
          docker tag ${{ env.SOURCE_IMAGE }} ${{ env.TARGET_IMAGE }}:latest
          docker tag ${{ env.SOURCE_IMAGE }} ${{ env.TARGET_IMAGE }}:${{ env.VERSION }}

      - name: Push retagged images
        if: ${{ github.event.inputs.force_push == 'true' }}
        run: |
          docker push ${{ env.TARGET_IMAGE }}:latest
          docker push ${{ env.TARGET_IMAGE }}:${{ env.VERSION }}
