name: Build and Push TRT Container

on:
  release:
    types: [created]

env:
  VERSION: '0.0.0' # Default version, will be overwritten

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v3
      -
        name: Read version from file
        run: echo "VERSION=$(DISABLE_VERSION_CHECK=true python ./inference/core/version.py)" >> $GITHUB_ENV
      -
        name: Build and Push Base Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: roboflow/roboflow-inference-server-trt-base:latest,roboflow/roboflow-inference-server-trt-base:${{ env.VERSION}}
          cache-from: type=registry,ref=roboflow/roboflow-inference-server-trt-base:cache
          cache-to: type=registry,ref=roboflow/roboflow-inference-server-trt-base:cache,mode=max
          platforms: linux/amd64
          file: ./docker/dockerfiles/Dockerfile.onnx.trt.base
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: roboflow/roboflow-inference-server-trt:latest,roboflow/roboflow-inference-server-trt:${{ env.VERSION}}
          cache-from: type=registry,ref=roboflow/roboflow-inference-server-trt:cache
          cache-to: type=registry,ref=roboflow/roboflow-inference-server-trt:cache,mode=max
          platforms: linux/amd64
          file: ./docker/dockerfiles/Dockerfile.onnx.trt