name: Docs Workflow

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: depot-ubuntu-22.04-small
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: inference_repo
      - uses: actions/checkout@v4
        with:
          repository: roboflow/workflows-enterprise-blocks
          ref: main
          path: roboflow_enterprise_blocks
          token: ${{ secrets.GH_TOKEN_FOR_WORKFLOWS_ENTERPRISE }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          check-latest: true
      - run: pip install mkdocs-material
      - run: pip install "mkdocstrings[python]"
      - run: pip install "mkdocs-material[imaging]"
      - run: pip install "mkdocs-swagger-ui-tag"
      - run: pip install "mkdocs-gen-files"
      - run: pip install "mkdocs-literate-nav"
      - run: pip install "mkdocs-jupyter"
      - run: pip install -r requirements/requirements.docs.txt
        working-directory: ./inference_repo
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements/_requirements.txt -r requirements/requirements.cpu.txt -r requirements/requirements.sdk.http.txt -r requirements/requirements.test.unit.txt -r requirements/requirements.test.integration.txt -r requirements/requirements.http.txt
        working-directory: ./inference_repo
      - run: pip install .
        working-directory: ./roboflow_enterprise_blocks
      - run: |
          python -m development.docs.build_block_docs
          WORKFLOWS_GALLERY_API_KEY=${{ secrets.WORKFLOWS_GALLERY_API_KEY }} python -m development.docs.workflows_gallery_builder
        working-directory: ./inference_repo
      - run: mkdocs gh-deploy --force
        working-directory: ./inference_repo
