name: mergeable

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  is_mergeable:
    runs-on:
      labels: depot-ubuntu-22.04-8
      group: public-depot
    timeout-minutes: 15
    steps:
      - name: üõéÔ∏è Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
          ref: main
      - name : Store main sha in context
        run: echo "main_sha=$(git rev-parse main)" >> "${GITHUB_ENV}"
      - name: Calculate depth
        run: echo "FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
      - name: üõéÔ∏è Checkout branch with all history
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check and store mergable state
        id: mergeable_check
        run: |
          echo "Check if main is ancestor of ${{ github.event.pull_request.head.sha }} (branch HEAD)";
          if $(git merge-base --is-ancestor ${{ env.main_sha }} ${{ github.event.pull_request.head.sha }}); then
            echo "Branch is mergeable";
            exit 0;
          else
            echo "Branch needs to be updated";
            exit 1;
          fi
