name: Test package install - inference-cli

on:
  pull_request:
    branches: [main]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on:
      group: group8core
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3
      - name: ğŸ Set up Python 3.9 to create wheels
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: ğŸ› Create Wheels
        run: |
          make create_wheels
      - name: ğŸ Set up Python ${{ matrix.python-version }} to test package install process
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: ğŸ“¦ Installing `inference` package...
        run: pip install ./dist/inference_cli-*-py3-none-any.whl
      - name: ğŸ§ª Testing package installation
        working-directory: "/"
        run: |
          python -c "import os; import platform; print(f'Python version: {platform.python_version()}'); print(f'CWD: {os.getcwd()}')"
          inference --help
        
