name: Code Quality & Regression Tests - Jetson 5.1.1
permissions:
  contents: read
on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !github.event.act }}
    runs-on: [self-hosted, jetson, jetpack-5.1.1]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: üõéÔ∏è Checkout
        uses: actions/checkout@v4
      - name: üì¶ Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - name: ü¶æ Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/requirements.test.integration.txt
      - name: üî® Build and Push Test Docker - Jetson 5.1.1
        run: |
          docker pull roboflow/roboflow-inference-server-jetson-5.1.1:test
          docker build -t roboflow/roboflow-inference-server-jetson-5.1.1:test -f docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1 .
          docker push roboflow/roboflow-inference-server-jetson-5.1.1:test
      
      - name: üîã Start Test Docker without Torch Preprocessing - Jetson 5.1.1
        run: |
          USE_INFERENCE_MODELS=false PORT=9101 USE_PYTORCH_FOR_PREPROCESSING=False INFERENCE_SERVER_REPO=roboflow-inference-server-jetson-5.1.1 make start_test_docker_jetson
      - name: üß™ Regression Tests without Torch Preprocessing - Jetson 5.1.1
        run: |
          SKIP_VISUALISATION_TESTS=true SKIP_LMM_TEST=True SKIP_PE_TEST=True MAX_WAIT=300 SKIP_GROUNDING_DINO_TEST=true SKIP_SAM_TEST=true SKIP_GAZE_TEST=true FUNCTIONAL=true PORT=9101 API_KEY=${{ secrets.API_KEY }} asl_instance_segmentation_API_KEY=${{ secrets.ASL_INSTANCE_SEGMENTATION_API_KEY }} asl_poly_instance_seg_API_KEY=${{ secrets.ASL_POLY_INSTANCE_SEG_API_KEY }} bccd_favz3_API_KEY=${{ secrets.BCCD_FAVZ3_API_KEY }} bccd_i4nym_API_KEY=${{ secrets.BCCD_I4NYM_API_KEY }} cats_and_dogs_smnpl_API_KEY=${{ secrets.CATS_AND_DOGS_SMNPL_API_KEY }} coins_xaz9i_API_KEY=${{ secrets.COINS_XAZ9I_API_KEY }} melee_API_KEY=${{ secrets.MELEE_API_KEY }} yolonas_test_API_KEY=${{ secrets.YOLONAS_TEST_API_KEY }} python -m pytest tests/inference/integration_tests/
      - name: üßπ Cleanup Test Docker - Jetson 5.1.1
        run: make stop_test_docker
        if: success() || failure()
      
      - name: üîã Start Test Docker with Torch Preprocessing - Jetson 5.1.1
        run: |
          PORT=9101 USE_PYTORCH_FOR_PREPROCESSING=True INFERENCE_SERVER_REPO=roboflow-inference-server-jetson-5.1.1 make start_test_docker_jetson
      - name: üß™ Regression Tests with Torch Preprocessing - Jetson 5.1.1
        run: |
          SKIP_VISUALISATION_TESTS=true SKIP_LMM_TEST=True MAX_WAIT=300 SKIP_PE_TEST=True SKIP_GROUNDING_DINO_TEST=true SKIP_SAM_TEST=true SKIP_GAZE_TEST=true FUNCTIONAL=true PORT=9101 API_KEY=${{ secrets.API_KEY }} asl_instance_segmentation_API_KEY=${{ secrets.ASL_INSTANCE_SEGMENTATION_API_KEY }} asl_poly_instance_seg_API_KEY=${{ secrets.ASL_POLY_INSTANCE_SEG_API_KEY }} bccd_favz3_API_KEY=${{ secrets.BCCD_FAVZ3_API_KEY }} bccd_i4nym_API_KEY=${{ secrets.BCCD_I4NYM_API_KEY }} cats_and_dogs_smnpl_API_KEY=${{ secrets.CATS_AND_DOGS_SMNPL_API_KEY }} coins_xaz9i_API_KEY=${{ secrets.COINS_XAZ9I_API_KEY }} melee_API_KEY=${{ secrets.MELEE_API_KEY }} yolonas_test_API_KEY=${{ secrets.YOLONAS_TEST_API_KEY }} python -m pytest tests/inference/integration_tests/
      - name: üßπ Cleanup Test Docker - Jetson 5.1.1
        run: make stop_test_docker
        if: success() || failure()
