name: Test package install - inference[extras]

on:
  pull_request:
    branches: [main]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on:
      group: group8core
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v3
      - name: ğŸ Set up Python 3.9 to create wheels
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: ğŸš§ Install GDAL OS library
        run: sudo apt-get install gdal-bin
      - name: ğŸ› Create Wheels
        run: |
          make create_wheels
      - name: ğŸ Set up Python ${{ matrix.python-version }} to test package install process
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: ğŸ“¦ Installing `inference` package...
        run: |
          wheel_name=`ls ./dist/inference-*-py3-none-any.whl | head -n 1`
          pip install "${wheel_name}[clip,gaze,grounding-dino,sam,waf,yolo-world,http,hosted]"
      - name: ğŸ§ª Testing package installation
        working-directory: "/"
        run: |
          python -c "import os; import platform; print(f'Python version: {platform.python_version()}'); print(f'CWD: {os.getcwd()}'); from inference import get_model"
          python -c "from inference.models.clip import Clip"
          python -c "from inference.models.gaze import Gaze"
          python -c "from inference.models.sam import SegmentAnything"
          python -c "from inference.models.grounding_dino import GroundingDINO"
          python -c "from inference.models.yolo_world import YOLOWorld"